#!/usr/bin/perl -w

#$canned = 1;

# args
if ($ARGV[0] && $ARGV[0] =~ /^\d{4}[mnwc]$/) {
	$tourney = $ARGV[0] || "2015m";
	shift;
}
else { $tourney = "2015m"; }
if ($ARGV[0] && $ARGV[0] =~ /^(\d{8})$/) { $date = $1; }

# common setup
scalar %game;  # suppress a warning about $game being used only once
require 'bracket.pl';
setup("$tourney/teams");
my @actual = @{(read_winners("$tourney/actual"))[0]};
foreach (keys %team) { $reverse{$team{$_}} = $_; }

# read the file we're about to clobber
open(ACTUAL, "$tourney/actual");
while (<ACTUAL>) {
	chomp;
	if (/^(\d+)\s+/) {
		$out{$1} = $_;
	}
}

# team short-name mappings
open(INP, "<teams-espn-map");
while (<INP>) {
	/(.*) => (.*)/ || next;
	$rename{$1} = $2;
}

# create %lookup array to map "$team1$team2" => game number
foreach my $g (1..31) {
	if ($actual[$g*2] && $actual[$g*2+1]) {
		$lookup{$team{$actual[$g*2]}.$team{$actual[$g*2+1]}} = $g;
		$lookup{$team{$actual[$g*2+1]}.$team{$actual[$g*2]}} = $g;
	}
}
foreach my $g (32..63) {
	my ($a, $b) = split/,/, $game{$g};
	next if !$team{$a} || !$team{$b};
	$lookup{$team{$a}.$team{$b}} = $g;
	$lookup{$team{$b}.$team{$a}} = $g;
}

# scrape an ESPN scoreboard page
my ($sport, $confId);
if ($tourney =~ /m$/) { $sport = "ncb"; $confId = 100; }
elsif ($tourney =~ /n$/) { $sport = "ncb"; $confId = 50; }
elsif ($tourney =~ /c$/) { $sport = "ncb"; $confId = 55; }
elsif ($tourney =~ /w$/) { $sport = "ncw"; $confId = 100; }
my $url = "http://sports.espn.go.com/$sport/scoreboard?confId=$confId";
if ($date) { $url .= "&date=$date"; }
print STDERR "$url\n";
if ($canned) {
	open(WGET, "<scoreboard.html");
}
else {
	open(WGET, "wget -qO - \"$url\"|") || die "wget: $!";
	open(SCOREBOARD, ">scoreboard.html");
}
$/ = "</div></div></div><div";
while (<WGET>) {
	my $current_game;
	my $g;
	print SCOREBOARD if !$canned;
	if (m!var\s+snapshotId\s+=\s+(\d+)!) {
		$snapshotId = $1;
	}
	if (m!aTeamName"><a title="([^"]+)" href="http://espn.go.com/mens-college-basketball/team/_/id/\d+/!) {
		$away = $1;
		$away = $rename{$away} || $away;
		#print STDERR "away=\"$away\"\n";
	}
	if (m!hTeamName"><a title="([^"]+)" href="http://espn.go.com/mens-college-basketball/team/_/id/\d+/!) {
		$home = $1;
		$home = $rename{$home} || $home;
		#print STDERR "home=\"$home\"\n";
	}
	if (m!(\d+)-gameHeader!) {
		$current_game = $1;
		$g = $lookup{$home.$away};
		if (!$g) {
			print STDERR "Can't find game number for \"$home\" vs. \"$away\"\n";
			next;
		}
		$espn_to_gameno{$current_game} = $g;
		$state{$g}{away} = $away;
		$state{$g}{home} = $home;
	}
	if (/-statusLine1">(Final[^<]*)/) {
		$state{$g}{clock} = $1;
		#print STDERR "clock=\"$state{$g}{clock}\"\n";
	}
	elsif (m!statusLine1">(?:&nbsp;|\s)*([^<]*)<!) {
		$state{$g}{clock} = $1;
		#print STDERR "clock=\"$state{$g}{clock}\"\n";
	}
	elsif (/class="time-remaining" style="display: inline">([0-9:]*)/) {
		$state{$g}{clock} = $1;
		#print STDERR "clock=\"$state{$g}{clock}\"\n";
	}
	if (/-awayHeaderScore">(\d+)<.*-homeHeaderScore">(\d+)</) {
		$state{$g}{away_score} = $1;
		$state{$g}{home_score} = $2;
		#print STDERR "score=\"$state{$g}{away_score}\" to \"$state{$g}{home_score}\"\n";
	}
}

#show_and_set_out();
get_snapshot();
show_and_set_out();

open(ACTUAL, ">$tourney/actual.new");
foreach (sort {$b <=> $a} keys %out) {
	print ACTUAL "$out{$_}\n";
}
rename("$tourney/actual.new", "$tourney/actual");

my %warned_not_found;
sub do_snapshot_command {
	my $gameno = $espn_to_gameno{$_[0]};
	my $str = $_[1];
	$str =~ tr/\r/\n/;
	#print STDERR "<COMMAND> [$gameno/$_[0]] $str\n";
	if (!$gameno) {
		print STDERR "Game \"$_[0]\" not found???\n" if !$warned_not_found{$_[0]}++;
		return;
	}
	if ($str =~ /^01(\w+)/) {      # home outcome (loser, winner)
		#print STDERR "[$gameno] Home team is: \"$1\"\n";
	}
	if ($str =~ /^02(\w+)/) {      # away outcome (loser, winner)
		#print STDERR "[$gameno] Away team is: \"$1\"\n";
	}
	if ($str =~ /^03(\d+)/) {      # away score
		#print STDERR "[$gameno] Away score is: \"$1\"\n";
		$state{$gameno}{away_score} = $1;
	}
	if ($str =~ /^04(\d+)/) {      # home score
		#print STDERR "[$gameno] Home score is: \"$1\"\n";
		$state{$gameno}{home_score} = $1;
	}
	if ($str =~ /^05(.nbsp;\s*)?(.+)/) {      # time label (Final)
		#print STDERR "[$gameno] Time is: \"$2\"\n";
		$state{$gameno}{clock} = $2;
	}
	if ($str =~ /^06(\w+)/) {      # period label (1st, 2nd, Halftime)
		#print STDERR "[$gameno] Period is: \"$1\"\n";
		my @tok = split/\s+/, $state{$gameno}{clock};
		$state{$gameno}{clock} = "$1 $tok[1]";
	}
	if ($str =~ /^07([0-9:]+)/) {  # time remaining (0:01, or &nbsp;)
		#print STDERR "[$gameno] Time remaining: \"$1\"\n";
		my @tok = split/\s+/, $state{$gameno}{clock};
		$state{$gameno}{clock} = "$tok[0] $1";
	}
	if ($str =~ /^1c(.*)/) {       # status message, terminated by \n or \r
		#print STDERR "[$gameno] Status: \"$1\"\n";
	}
}

sub show_and_set_out {
	foreach $g (sort { timeleft($state{$a}{clock}) <=> timeleft($state{$b}{clock}) } keys %state) {
		next if !defined $state{$g}{home_score} && !defined $state{$g}{away_score};
		my ($ot) = $state{$g}{clock} =~ /^Final - (\d*)\w*\s*OT/;
		$ot = defined $ot ? " ${ot}OT" : "";
		my $gstring;
		if ($state{$g}{home_score} > $state{$g}{away_score}) {
			$gstring = "$g $reverse{$state{$g}{home}} $state{$g}{home_score}-$state{$g}{away_score}$ot";
			$out{$g} = $gstring if $state{$g}{clock} =~ /^Final/;
		}
		else {
			$gstring = "$g $reverse{$state{$g}{away}} $state{$g}{away_score}-$state{$g}{home_score}$ot";
			$out{$g} = $gstring if $state{$g}{clock} =~ /^Final/;
		}
		printf STDERR "%-20s # %16s  %-27s    %s\n",
			$gstring, "[$state{$g}{clock}]", "($reverse{$state{$g}{home}}) $state{$g}{home} - $state{$g}{home_score}",
			"($reverse{$state{$g}{away}}) $state{$g}{away} - $state{$g}{away_score}";
	}
}

sub timeleft {
	if ($_[0] =~ /^Final\b/) { return 0; }
	if ($_[0] eq "Halftime") { return 20*60; }
	if ($_[0] =~ /(\d+):(\d+) 1st/) { return $1*60 + $2 + 20*60; }
	if ($_[0] =~ /(\d+):(\d+) 2nd/) { return $1*60 + $2; }
	if ($_[0] =~ /(\d+):(\d+) PM/) { return $1*3600 + $2*60 + 40*60; }
	print STDERR "timeleft?? \"$_[0]\"\n";
	return 0;
}

sub get_snapshot {
	if ($sport eq "ncb" && $snapshotId) {
		$/ = "\n";
		if ($canned) {
			open(WGET, "<snapshot.xml");
		}
		else {
			print STDERR "Getting snapshot $snapshotId\n";
			$url = "http://scores.espn.go.com/ncb/caster/snapshot?sessionId=ncbScoreboard09&masterSnap=$snapshotId&casterSnap=$snapshotId&rand=1300392054758";
			open(WGET, "wget -qO - \"$url\"|") || die "wget: $!";
			open(SNAPSHOT, ">snapshot.xml");
		}
		while (<WGET>) {
			print SNAPSHOT if !$canned;
			chomp;
			foreach my $line (split/\r/, $_) {
				if ($line =~ m!\]\]!) { undef $snapshot_game; }
				if ($line =~ m/<Snapshot snapshotId="\d+"><!\[CDATA\[(\d+)\s+(.*)/) {
					$snapshot_game = $1;
					do_snapshot_command($snapshot_game, $2);
				}
				elsif ($snapshot_game) {
					if ($line =~ m!^(\d{9})\s+(.*)!) {
						$snapshot_game = $1;
						do_snapshot_command($snapshot_game, $2);
					}
					else {
						do_snapshot_command($snapshot_game, $line);
					}
				}
			}
		}
	}
}
